spring.application.name=service-product
server.port=8011

spring.cloud.nacos.server-addr=127.0.0.1:8848
# if can`t user nacos for config, but import common dependence from parent pom, then use this to ignore nacos check
spring.cloud.nacos.config.import-check.enabled=false