spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          product-feign-client: # high priority
            logger-level: full
            connect-timeout: 3000
            read-timeout: 2000
#            request-interceptors:
#              - com.spc.order.interceptor.XTokenRequestInterceptor # config request interceptor
#            retryer: feign.retryer.Default