#spring.application.name=service-order
#server.port=8001
#
#
## if nacos and project config same properties with same time, then use nacos config
#order.timeout=70min
#order.auto-confirm=90d
#
#spring.cloud.nacos.server-addr=127.0.0.1:8848
#spring.config.import=nacos:service-order.properties,nacos:common.properties
#spring.cloud.nacos.config.import-check.enabled=false